name: cslysy.github.io
description: One does not simply be good at programming
meta_description: "One does not simply be good at programming"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://cslysy.github.io'
google_analytics: 'UA-76149595-1'

# Details for the RSS feed generator
url: 'http://cslysy.github.io/'

gems: [jekyll-paginate]
